spring:
  application:
    name: thesis
  profiles:
    active: init-data
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thesis
    username: root
    password: secret

server:
    port: 8080
    servlet:
      context-path: /thesis
